"""Tests for GGUF / Ollama Modelfile generation + template round-trip verification."""

from bashgym.export.gguf import (
    ModelfileSpec,
    build_modelfile,
    check_template_roundtrip,
    parse_ollama_modelfile,
)

# A trimmed but representative `ollama show <model> --modelfile` output.
SAMPLE_OLLAMA_MODELFILE = '''# Modelfile generated by "ollama show"
FROM /root/.ollama/models/blobs/sha256-abc

TEMPLATE """{{- if .System }}<start_of_turn>system
{{ .System }}<end_of_turn>
{{ end }}<start_of_turn>user
{{ .Prompt }}<end_of_turn>
<start_of_turn>model
"""
PARAMETER stop "<end_of_turn>"
PARAMETER stop "<eos>"
PARAMETER temperature 1
'''


class TestBuildModelfile:
    def test_includes_from_template_stops_params(self):
        mf = build_modelfile(
            ModelfileSpec(
                from_path="/models/run/merged.gguf",
                template="<start_of_turn>user\n{{ .Prompt }}<end_of_turn>",
                system="You are helpful.",
                stop_tokens=("<end_of_turn>", "<eos>"),
                parameters={"temperature": 0.7, "num_ctx": 8192},
            )
        )
        assert "FROM /models/run/merged.gguf" in mf
        assert 'TEMPLATE """<start_of_turn>user' in mf
        assert 'SYSTEM """You are helpful."""' in mf
        assert 'PARAMETER stop "<end_of_turn>"' in mf
        assert 'PARAMETER stop "<eos>"' in mf
        assert "PARAMETER temperature 0.7" in mf
        assert "PARAMETER num_ctx 8192" in mf

    def test_no_template_line_when_empty(self):
        # The bug being fixed: omitting TEMPLATE. We still allow it, but it must be
        # an explicit empty-template choice, not a silent default.
        mf = build_modelfile(ModelfileSpec(from_path="x.gguf"))
        assert "FROM x.gguf" in mf
        assert "TEMPLATE" not in mf


class TestParseOllamaModelfile:
    def test_extracts_template_and_stops(self):
        template, stops = parse_ollama_modelfile(SAMPLE_OLLAMA_MODELFILE)
        assert "<start_of_turn>user" in template
        assert stops == ("<end_of_turn>", "<eos>")

    def test_build_then_parse_roundtrips_template(self):
        template = "<start_of_turn>user\n{{ .Prompt }}<end_of_turn>"
        mf = build_modelfile(
            ModelfileSpec(from_path="x.gguf", template=template, stop_tokens=("<end_of_turn>",))
        )
        parsed_template, parsed_stops = parse_ollama_modelfile(mf)
        assert parsed_template.strip() == template.strip()
        assert parsed_stops == ("<end_of_turn>",)


class TestCheckTemplateRoundtrip:
    def test_identical_renders_ok(self):
        render = "<bos><start_of_turn>user\nhi<end_of_turn>"
        v = check_template_roundtrip(render, render)
        assert v.ok and v.issues == []

    def test_double_bos_flagged(self):
        train = "<bos><start_of_turn>user\nhi<end_of_turn>"
        serve = "<bos><bos><start_of_turn>user\nhi<end_of_turn>"
        v = check_template_roundtrip(train, serve)
        assert not v.ok
        assert any("double-BOS" in i for i in v.issues)

    def test_missing_required_token_flagged(self):
        train = "<start_of_turn>model\n<|tool_call>call:f{}<tool_call|>"
        serve = "<start_of_turn>model\n(no tool tokens)"
        v = check_template_roundtrip(train, serve, required_tokens=("<|tool_call>",))
        assert not v.ok
        assert any("dropped required token" in i for i in v.issues)

    def test_differing_renders_flagged(self):
        v = check_template_roundtrip("aaa", "bbb")
        assert not v.ok
        assert any("differ" in i for i in v.issues)
